# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/seuleee/my_cvui/cvui

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/seuleee/my_cvui/cvui

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seuleee/my_cvui/cvui/CMakeFiles /home/seuleee/my_cvui/cvui/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seuleee/my_cvui/cvui/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named button-shortcut

# Build rule for target.
button-shortcut: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 button-shortcut
.PHONY : button-shortcut

# fast build rule for target.
button-shortcut/fast:
	$(MAKE) -f example/src/button-shortcut/CMakeFiles/button-shortcut.dir/build.make example/src/button-shortcut/CMakeFiles/button-shortcut.dir/build
.PHONY : button-shortcut/fast

#=============================================================================
# Target rules for targets named canny

# Build rule for target.
canny: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 canny
.PHONY : canny

# fast build rule for target.
canny/fast:
	$(MAKE) -f example/src/canny/CMakeFiles/canny.dir/build.make example/src/canny/CMakeFiles/canny.dir/build
.PHONY : canny/fast

#=============================================================================
# Target rules for targets named complex-layout

# Build rule for target.
complex-layout: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 complex-layout
.PHONY : complex-layout

# fast build rule for target.
complex-layout/fast:
	$(MAKE) -f example/src/complext-layout/CMakeFiles/complex-layout.dir/build.make example/src/complext-layout/CMakeFiles/complex-layout.dir/build
.PHONY : complex-layout/fast

#=============================================================================
# Target rules for targets named hello-world

# Build rule for target.
hello-world: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello-world
.PHONY : hello-world

# fast build rule for target.
hello-world/fast:
	$(MAKE) -f example/src/hello-world/CMakeFiles/hello-world.dir/build.make example/src/hello-world/CMakeFiles/hello-world.dir/build
.PHONY : hello-world/fast

#=============================================================================
# Target rules for targets named image-button

# Build rule for target.
image-button: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 image-button
.PHONY : image-button

# fast build rule for target.
image-button/fast:
	$(MAKE) -f example/src/image-button/CMakeFiles/image-button.dir/build.make example/src/image-button/CMakeFiles/image-button.dir/build
.PHONY : image-button/fast

#=============================================================================
# Target rules for targets named interaction-area

# Build rule for target.
interaction-area: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interaction-area
.PHONY : interaction-area

# fast build rule for target.
interaction-area/fast:
	$(MAKE) -f example/src/interaction-area/CMakeFiles/interaction-area.dir/build.make example/src/interaction-area/CMakeFiles/interaction-area.dir/build
.PHONY : interaction-area/fast

#=============================================================================
# Target rules for targets named main-app

# Build rule for target.
main-app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main-app
.PHONY : main-app

# fast build rule for target.
main-app/fast:
	$(MAKE) -f example/src/main-app/CMakeFiles/main-app.dir/build.make example/src/main-app/CMakeFiles/main-app.dir/build
.PHONY : main-app/fast

#=============================================================================
# Target rules for targets named mouse

# Build rule for target.
mouse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mouse
.PHONY : mouse

# fast build rule for target.
mouse/fast:
	$(MAKE) -f example/src/mouse/CMakeFiles/mouse.dir/build.make example/src/mouse/CMakeFiles/mouse.dir/build
.PHONY : mouse/fast

#=============================================================================
# Target rules for targets named mouse-complex

# Build rule for target.
mouse-complex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mouse-complex
.PHONY : mouse-complex

# fast build rule for target.
mouse-complex/fast:
	$(MAKE) -f example/src/mouse-complex/CMakeFiles/mouse-complex.dir/build.make example/src/mouse-complex/CMakeFiles/mouse-complex.dir/build
.PHONY : mouse-complex/fast

#=============================================================================
# Target rules for targets named mouse-complex-buttons

# Build rule for target.
mouse-complex-buttons: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mouse-complex-buttons
.PHONY : mouse-complex-buttons

# fast build rule for target.
mouse-complex-buttons/fast:
	$(MAKE) -f example/src/mouse-complex-buttons/CMakeFiles/mouse-complex-buttons.dir/build.make example/src/mouse-complex-buttons/CMakeFiles/mouse-complex-buttons.dir/build
.PHONY : mouse-complex-buttons/fast

#=============================================================================
# Target rules for targets named multiple-files

# Build rule for target.
multiple-files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multiple-files
.PHONY : multiple-files

# fast build rule for target.
multiple-files/fast:
	$(MAKE) -f example/src/multiple-files/CMakeFiles/multiple-files.dir/build.make example/src/multiple-files/CMakeFiles/multiple-files.dir/build
.PHONY : multiple-files/fast

#=============================================================================
# Target rules for targets named multiple-windows

# Build rule for target.
multiple-windows: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multiple-windows
.PHONY : multiple-windows

# fast build rule for target.
multiple-windows/fast:
	$(MAKE) -f example/src/multiple-windows/CMakeFiles/multiple-windows.dir/build.make example/src/multiple-windows/CMakeFiles/multiple-windows.dir/build
.PHONY : multiple-windows/fast

#=============================================================================
# Target rules for targets named multiple-windows-complex

# Build rule for target.
multiple-windows-complex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multiple-windows-complex
.PHONY : multiple-windows-complex

# fast build rule for target.
multiple-windows-complex/fast:
	$(MAKE) -f example/src/multiple-windows-complex/CMakeFiles/multiple-windows-complex.dir/build.make example/src/multiple-windows-complex/CMakeFiles/multiple-windows-complex.dir/build
.PHONY : multiple-windows-complex/fast

#=============================================================================
# Target rules for targets named multiple-windows-complex-dynamic

# Build rule for target.
multiple-windows-complex-dynamic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multiple-windows-complex-dynamic
.PHONY : multiple-windows-complex-dynamic

# fast build rule for target.
multiple-windows-complex-dynamic/fast:
	$(MAKE) -f example/src/multiple-windows-complex-dynamic/CMakeFiles/multiple-windows-complex-dynamic.dir/build.make example/src/multiple-windows-complex-dynamic/CMakeFiles/multiple-windows-complex-dynamic.dir/build
.PHONY : multiple-windows-complex-dynamic/fast

#=============================================================================
# Target rules for targets named multiple-windows-complex-mouse

# Build rule for target.
multiple-windows-complex-mouse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multiple-windows-complex-mouse
.PHONY : multiple-windows-complex-mouse

# fast build rule for target.
multiple-windows-complex-mouse/fast:
	$(MAKE) -f example/src/multiple-windows-complex-mouse/CMakeFiles/multiple-windows-complex-mouse.dir/build.make example/src/multiple-windows-complex-mouse/CMakeFiles/multiple-windows-complex-mouse.dir/build
.PHONY : multiple-windows-complex-mouse/fast

#=============================================================================
# Target rules for targets named nested-rows-columns

# Build rule for target.
nested-rows-columns: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nested-rows-columns
.PHONY : nested-rows-columns

# fast build rule for target.
nested-rows-columns/fast:
	$(MAKE) -f example/src/nested-rows-columns/CMakeFiles/nested-rows-columns.dir/build.make example/src/nested-rows-columns/CMakeFiles/nested-rows-columns.dir/build
.PHONY : nested-rows-columns/fast

#=============================================================================
# Target rules for targets named on-image

# Build rule for target.
on-image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 on-image
.PHONY : on-image

# fast build rule for target.
on-image/fast:
	$(MAKE) -f example/src/on-image/CMakeFiles/on-image.dir/build.make example/src/on-image/CMakeFiles/on-image.dir/build
.PHONY : on-image/fast

#=============================================================================
# Target rules for targets named row-column

# Build rule for target.
row-column: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 row-column
.PHONY : row-column

# fast build rule for target.
row-column/fast:
	$(MAKE) -f example/src/row-column/CMakeFiles/row-column.dir/build.make example/src/row-column/CMakeFiles/row-column.dir/build
.PHONY : row-column/fast

#=============================================================================
# Target rules for targets named sparkline

# Build rule for target.
sparkline: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sparkline
.PHONY : sparkline

# fast build rule for target.
sparkline/fast:
	$(MAKE) -f example/src/sparkline/CMakeFiles/sparkline.dir/build.make example/src/sparkline/CMakeFiles/sparkline.dir/build
.PHONY : sparkline/fast

#=============================================================================
# Target rules for targets named trackbar

# Build rule for target.
trackbar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trackbar
.PHONY : trackbar

# fast build rule for target.
trackbar/fast:
	$(MAKE) -f example/src/trackbar/CMakeFiles/trackbar.dir/build.make example/src/trackbar/CMakeFiles/trackbar.dir/build
.PHONY : trackbar/fast

#=============================================================================
# Target rules for targets named trackbar-complex

# Build rule for target.
trackbar-complex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trackbar-complex
.PHONY : trackbar-complex

# fast build rule for target.
trackbar-complex/fast:
	$(MAKE) -f example/src/trackbar-complex/CMakeFiles/trackbar-complex.dir/build.make example/src/trackbar-complex/CMakeFiles/trackbar-complex.dir/build
.PHONY : trackbar-complex/fast

#=============================================================================
# Target rules for targets named trackbar-sparkline

# Build rule for target.
trackbar-sparkline: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trackbar-sparkline
.PHONY : trackbar-sparkline

# fast build rule for target.
trackbar-sparkline/fast:
	$(MAKE) -f example/src/trackbar-sparkline/CMakeFiles/trackbar-sparkline.dir/build.make example/src/trackbar-sparkline/CMakeFiles/trackbar-sparkline.dir/build
.PHONY : trackbar-sparkline/fast

#=============================================================================
# Target rules for targets named ui-enhanced-canny

# Build rule for target.
ui-enhanced-canny: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ui-enhanced-canny
.PHONY : ui-enhanced-canny

# fast build rule for target.
ui-enhanced-canny/fast:
	$(MAKE) -f example/src/ui-enhanced-canny/CMakeFiles/ui-enhanced-canny.dir/build.make example/src/ui-enhanced-canny/CMakeFiles/ui-enhanced-canny.dir/build
.PHONY : ui-enhanced-canny/fast

#=============================================================================
# Target rules for targets named ui-enhanced-window-component

# Build rule for target.
ui-enhanced-window-component: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ui-enhanced-window-component
.PHONY : ui-enhanced-window-component

# fast build rule for target.
ui-enhanced-window-component/fast:
	$(MAKE) -f example/src/ui-enhanced-window-component/CMakeFiles/ui-enhanced-window-component.dir/build.make example/src/ui-enhanced-window-component/CMakeFiles/ui-enhanced-window-component.dir/build
.PHONY : ui-enhanced-window-component/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... button-shortcut"
	@echo "... canny"
	@echo "... complex-layout"
	@echo "... hello-world"
	@echo "... image-button"
	@echo "... interaction-area"
	@echo "... main-app"
	@echo "... mouse"
	@echo "... mouse-complex"
	@echo "... mouse-complex-buttons"
	@echo "... multiple-files"
	@echo "... multiple-windows"
	@echo "... multiple-windows-complex"
	@echo "... multiple-windows-complex-dynamic"
	@echo "... multiple-windows-complex-mouse"
	@echo "... nested-rows-columns"
	@echo "... on-image"
	@echo "... row-column"
	@echo "... sparkline"
	@echo "... trackbar"
	@echo "... trackbar-complex"
	@echo "... trackbar-sparkline"
	@echo "... ui-enhanced-canny"
	@echo "... ui-enhanced-window-component"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

